### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by ThomasSeeker** [shin0x/Surfshark-Killswitch-Linux#1]
Hey Jonah,

thank you very much for the Killswitch! ... it seems to work perfectly here.

One question though: Can you give a hint, on how to enable the switch after every boot?
Right now the connection stays "killed" after a reboot ... as it should (sort of).

Best greetings from Germany!
Thomas

**Comment by shin0x** [comment]
If I understood your problem correctly and you wanted to have an active Internet connection after your computer restarted then this should be now possible with the new commit. Just use the iptableskillswitch file now instead of the enableKillSwitch. And also you can now use the restoreiptables file instead the disableKillSwitch. But that one should work just as fine.

**Comment by ThomasSeeker** [comment]
Wow! That sounds perfect! ... Thank you very much!
